---
argument_specs:
  main:
    short_description: "Main entrypoint for the container_init role."
    options:
      container_conf:
        type: "dict"
        required: true
        description: "Metadata for container initialization."
        options:
          owner:
            type: "str"
            required: true
            description: "User account to host the created container."
          name:
            type: "str"
            required: true
            description: "Name assigned to the container."
          repo:
            type: "str"
            required: true
            description: "Container registry where the container image lives."
          image:
            type: "str"
            required: true
            description: "Name of the image in the container registry (e.g. user/image)."
          tag:
            type: "str"
            required: true
            description: "The tag used to fetch the container image."
          uid:
            type: "int"
            default: 0
            description: "The UID (in the containers namespace) that the primary process should run under."
          gid:
            type: "int"
            default: 0
            description: "The GID (in the containers namespace) that the primary process should run under."
          volumes:
            type: "list"
            elements: "str"
            default: []
            description: "List of volumes in docker mount format (e.g. /external:/internal:Z)."
          ports:
            type: "list"
            elements: "str"
            default: []
            description: "List of ports to expose on the host in docker format (e.g. 80:8080)."
          env:
            type: "dict"
            default: {}
            description: "Dictionary of environment variables to pass to the container runtime."
          command:
            type: "list"
            elements: "str"
            description: "Command to overwrite the container image's default CMD."
          podman_args:
            type: "list"
            elements: "str"
            description: "Additional arguments to pass podman in cli format."
