---
# handlers file for container_init
- name: (Re)start containers
  become_user: "{{ item.owner }}"
  systemd:
    name: "{{ item.prefix | default(default_prefix) }}-{{ item.name }}"
    state: restarted
    scope: user
  loop: "{{ container_restart_queue }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Flush (Re)start queue

# If (Re)start containers somehow runs multiple
#  times it will restart services more then once.
#  This handler solves that issue by clearing the queue.
- name: Flush (Re)start queue
  set_fact:
    container_restart_queue: []
